"""Numpyro inference engines for prophet models.

The classes in this module take a model, the data and perform inference using Numpyro.
"""

from collections.abc import Sequence
from typing import Any, Literal, Optional

import jax
from jax.random import PRNGKey
from skbase.base import BaseObject


class BaseInferenceEngine(BaseObject):
    """
    Class representing an inference engine for a given model.

    Parameters
    ----------
    rng_key : Optional[jax.random.PRNGKey]
        The random number generator key. If not provided, a default key with value 0
        will be used.

    Attributes
    ----------
    rng_key : jax.random.PRNGKey
        Random number generator key.

    model_ : Callable
        The model used for inference.
    """

    _tags = {
        "object_type": "inference_engine",
    }

    def __init__(self, rng_key=None):
        if rng_key is None:
            rng_key = jax.random.PRNGKey(0)

        self.rng_key = rng_key

        super().__init__()

    # pragma: no cover
    def infer(self, model, **kwargs):
        """
        Perform inference using the specified model.

        Parameters
        ----------
        model: Callable
            Model to perform inference for.
        **kwargs
            Additional keyword arguments to be passed to the model.

        Returns
        -------
        The result of the inference.
        """
        self.model_ = model
        self._infer(**kwargs)

    # pragma: no cover
    def _infer(self, **kwargs):  # pragma: no cover
        """
        Perform inference using the specified model.

        Parameters
        ----------
        **kwargs
            Additional keyword arguments to be passed to the model.

        Returns
        -------
        The result of the inference.
        """
        raise NotImplementedError("infer method must be implemented in subclass")

    # pragma: no cover
    def predict(self, **kwargs):
        """
        Generate predictions using the specified model.

        Parameters
        ----------
        **kwargs
            Additional keyword arguments to be passed to the model.

        Returns
        -------
        The predictions generated by the model.
        """
        return self._predict(**kwargs)

    # pragma: no cover
    def _predict(self, **kwargs):  # pragma: no cover
        """
        Generate predictions using the specified model.

        Parameters
        ----------
        **kwargs
            Additional keyword arguments to be passed to the model.

        Returns
        -------
        The predictions generated by the model.
        """
        raise NotImplementedError("predict method must be implemented in subclass")

    # pragma: no cover
    def update(
        self,
        site_names: Optional[Sequence[str]] = None,
        mode: Literal["full", "mean"] = "mean",
        **kwargs
    ):  # pragma: no cover
        """
        Update some or all samples.

        Parameters
        ----------
        site_names : Sequence[str]
            Site names to update.
        mode : Literal["full", "mean"], default "mean"
            Whether to update for each sample, or use mean of posterior samples not in ``site_names``.
        **kwargs
            Additional keyword arguments to be passed to the model.

        Returns
        -------
        Nothing.
        """

        if site_names is None or not site_names:
            return self.infer(self.model_, **kwargs)

        return self._update(site_names, mode, **kwargs)

    # pragma: no cover
    def _update(
        self, site_names: Sequence[str], mode: Literal["full", "mean"], **kwargs
    ):  # pragma: no cover
        """
        See :meth:`update`.
        """
        return self.infer(self.model_, **kwargs)
