# Function reference {.doc .doc-index}

## Sktime

Sktime models

| | |
| --- | --- |
| [Prophetverse](Prophetverse.qmd#prophetverse.sktime.Prophetverse) | Univariate Prophetverse forecaster with multiple likelihood options. |
| [HierarchicalProphet](HierarchicalProphet.qmd#prophetverse.sktime.HierarchicalProphet) | A Bayesian hierarchical time series forecasting model based on Meta's Prophet. |

## Exogenous effects

Exogenous effects

| | |
| --- | --- |
| [LinearEffect](LinearEffect.qmd#prophetverse.effects.LinearEffect) | Represents a linear effect in a hierarchical prophet model. |
| [LinearFourierSeasonality](LinearFourierSeasonality.qmd#prophetverse.effects.LinearFourierSeasonality) | Linear Fourier Seasonality effect. |
| [LogEffect](LogEffect.qmd#prophetverse.effects.LogEffect) | Represents a log effect as effect = scale * log(rate * data + 1). |
| [HillEffect](HillEffect.qmd#prophetverse.effects.HillEffect) | Represents a Hill effect in a time series model. |
| [ChainedEffects](ChainedEffects.qmd#prophetverse.effects.ChainedEffects) | Chains multiple effects sequentially, applying them one after the other. |
| [GeometricAdstockEffect](GeometricAdstockEffect.qmd#prophetverse.effects.GeometricAdstockEffect) | Represents a Geometric Adstock effect in a time series model. |

## MMM Likelihoods

MMM Likelihoods

| | |
| --- | --- |
| [LiftExperimentLikelihood](LiftExperimentLikelihood.qmd#prophetverse.effects.LiftExperimentLikelihood) | Wrap an effect and applies a normal likelihood to its output. |
| [ExactLikelihood](ExactLikelihood.qmd#prophetverse.effects.ExactLikelihood) | Wrap an effect and applies a normal likelihood to its output. |

## Trends

Trends

| | |
| --- | --- |
| [PiecewiseLinearTrend](PiecewiseLinearTrend.qmd#prophetverse.effects.PiecewiseLinearTrend) | Piecewise Linear Trend model. |
| [PiecewiseLogisticTrend](PiecewiseLogisticTrend.qmd#prophetverse.effects.PiecewiseLogisticTrend) | Piecewise logistic trend model. |
| [FlatTrend](FlatTrend.qmd#prophetverse.effects.FlatTrend) | Flat trend model. |

## Target Likelihoods

Likelihoods for the target variable

| | |
| --- | --- |
| [MultivariateNormal](MultivariateNormal.qmd#prophetverse.effects.MultivariateNormal) | Base class for effects. |
| [NormalTargetLikelihood](NormalTargetLikelihood.qmd#prophetverse.effects.NormalTargetLikelihood) |  |
| [GammaTargetLikelihood](GammaTargetLikelihood.qmd#prophetverse.effects.GammaTargetLikelihood) |  |
| [NegativeBinomialTargetLikelihood](NegativeBinomialTargetLikelihood.qmd#prophetverse.effects.NegativeBinomialTargetLikelihood) |  |

## Budget Optimization

Budget Optimization

| | |
| --- | --- |
| [BudgetOptimizer](BudgetOptimizer.qmd#prophetverse.experimental.budget_optimization.optimizer.BudgetOptimizer) | Budget optimizer using scipy.optimize.minimize. |

## Budget Constraints

Budget Constraints

| | |
| --- | --- |
| [SharedBudgetConstraint](SharedBudgetConstraint.qmd#prophetverse.experimental.budget_optimization.constraints.SharedBudgetConstraint) | Shared budget constraint. |
| [MinimumTargetResponse](MinimumTargetResponse.qmd#prophetverse.experimental.budget_optimization.constraints.MinimumTargetResponse) | Minimum target response constraint. |

## Objective Functions

Objective Functions

| | |
| --- | --- |
| [MinimizeBudget](MinimizeBudget.qmd#prophetverse.experimental.budget_optimization.objectives.MinimizeBudget) | Minimize budget constraint objective function. |
| [MaximizeKPI](MaximizeKPI.qmd#prophetverse.experimental.budget_optimization.objectives.MaximizeKPI) | Maximize the KPI objective function. |
| [MaximizeROI](MaximizeROI.qmd#prophetverse.experimental.budget_optimization.objectives.MaximizeROI) | Maximize return on investment (ROI) objective function. |

## Budget Parametrizations

Budget Parametrizations